services:
  postgres:
    image: postgres:17.6
    restart: always
    env_file: 
      - ./server/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./server
    restart: always
    ports:
      - '1111:1111'
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    
  frontend:
    build: ./client
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./client/.env
    depends_on:
      - backend
    
volumes:
  pg_data: